FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt
# Additionally install pytest dependency
RUN pip install --no-cache-dir pytest

# Set the entrypoint to run tests using pytest
CMD ["pytest"]