services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:///./app.db
    volumes:
      - ./app:/code/app

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./app:/code/app
    entrypoint: ["pytest"]